import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, ArrowUpRight, CalendarDays, Plus } from "lucide-react";
import { getSession } from "@/server/http/session";
import { prisma } from "@/server/db/client";
import type { ReleaseStatus } from "@/generated/prisma/client";

export default async function ReleasesPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  const session = await getSession(); if (!session) redirect("/login");
  const params=await searchParams;const query=(params.q??"").trim().slice(0,120);const statuses:ReleaseStatus[]=["DRAFT","SUBMITTED","IN_REVIEW","CHANGES_REQUESTED","RESUBMITTED","APPROVED","READY_FOR_DISTRIBUTION","DISTRIBUTED","SCHEDULED","RELEASED","REJECTED"];const selectedStatus=statuses.find((status)=>status===params.status);
  const staff = session.user.role !== "USER";
  const releases = await prisma.release.findMany({ where: { deletedAt: null, ...(staff ? {} : { ownerId: session.user.id }),...(selectedStatus?{status:selectedStatus}:{}),...(query?{OR:[{title:{contains:query,mode:"insensitive"}},{artists:{some:{artist:{name:{contains:query,mode:"insensitive"}}}}}]}:{}) }, include: { artists: { include: { artist: true } }, _count: { select: { tracks: true } } }, orderBy: { updatedAt: "desc" } });
  return <main className="subpage"><header className="subpage-head"><Link className="wizard-back" href="/"><ArrowLeft size={14}/> Overview</Link><Link href="/releases/new" className="primary-button"><Plus size={16}/> New release</Link></header><div className="subpage-content"><div className="section-kicker">YOUR CATALOG</div><h1>Releases</h1><p className="subpage-intro">Every track, every milestone, in one place.</p><form className="release-filters"><label><span>Search</span><input name="q" defaultValue={query} placeholder="Title or artist"/></label><label><span>Status</span><select name="status" defaultValue={selectedStatus ?? ""}><option value="">All statuses</option>{statuses.map(item=><option key={item} value={item}>{item.toLowerCase().replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}</option>)}</select></label><button className="filter-button">Apply filters</button>{(query||selectedStatus)&&<Link href="/releases" className="clear-filter">Clear</Link>}</form>{releases.length===0?<div className="empty-state"><b>No releases found</b><span>{query||selectedStatus?"Try a different search or status filter.":"Your new release will appear here."}</span></div>:<div className="table-wrap"><table className="release-table"><thead><tr><th>RELEASE</th><th>TYPE</th><th>STATUS</th><th>RELEASE DATE</th><th>UPDATED</th><th/></tr></thead><tbody>{releases.map((release,index)=>{const status=release.status.toLowerCase().replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());return <tr key={release.id}><td><Link href={`/releases/${release.id}`} className="table-release"><span className={`table-cover cover-${["blue","sand","rose","green"][index%4]}`}>{release.title.slice(0,2).toUpperCase()}</span><span><b>{release.title}</b><small>{release.artists.map(x=>x.artist.name).join(", ")||session.user.name}</small></span></Link></td><td>{release.type} · {release._count.tracks} {release._count.tracks===1?"track":"tracks"}</td><td><span className={`status status-${status.toLowerCase().replaceAll(" ","-")}`}><i/>{status}</span></td><td>{release.desiredDate?new Intl.DateTimeFormat("en",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(release.desiredDate):"—"}</td><td>{new Intl.DateTimeFormat("en",{day:"2-digit",month:"short",timeZone:"UTC"}).format(release.updatedAt)}</td><td><Link href={`/releases/${release.id}`} aria-label={`Open ${release.title}`}><ArrowUpRight size={15}/></Link></td></tr>})}</tbody></table></div>}<footer className="page-footer"><span>© 2026 NynetyDegrees Records</span><span><CalendarDays size={12}/> Dates shown in UTC</span></footer></div></main>;
}
