import Link from "next/link";
import { redirect } from "next/navigation";
import { Activity, ArrowUpRight, AudioLines, CalendarDays, ChevronDown, CircleHelp, Disc3, LayoutDashboard, Plus, Search, Settings2, SlidersHorizontal, Sparkles, UsersRound, type LucideIcon } from "lucide-react";
import { getSession } from "@/server/http/session";
import { prisma } from "@/server/db/client";

type ReleaseCardData = { id: string; title: string; artist: string; type: string; date: string; status: string; tone: string; cover: string; artworkUrl?: string };
const nav: { name: string; icon: LucideIcon; active?: boolean }[] = [{ name: "Overview", icon: LayoutDashboard, active: true }, { name: "Releases", icon: Disc3 }, { name: "Artists", icon: UsersRound }];

function Status({ value }: { value: string }) {
  const kind = value.toLowerCase().replaceAll(" ", "-");
  return <span className={`status status-${kind}`}><i />{value}</span>;
}

function ReleaseCard({ release }: { release: ReleaseCardData }) {
  return <Link href={`/releases/${release.id}`} className="release-card"><div className={`artwork ${release.tone}`} style={release.artworkUrl ? { backgroundImage: `url("${release.artworkUrl}")`, backgroundSize: "cover", backgroundPosition: "center" } : undefined} aria-label={`${release.title} cover art`}>{!release.artworkUrl && <span>{release.cover}</span>}<small>90°</small></div><div className="release-meta"><div className="release-title"><div><h3>{release.title}</h3><p>{release.artist} <span>·</span> {release.type}</p></div><ArrowUpRight className="release-open-icon" size={14}/></div><div className="release-bottom"><Status value={release.status} /><span className="release-date"><CalendarDays size={13} />{release.date}</span></div></div></Link>;
}

export default async function Home() {
  const session = await getSession();
  if (!session) redirect("/login");
  const isStaff = session.user.role === "MANAGER" || session.user.role === "ADMIN";
  const where = { deletedAt: null, ...(isStaff ? {} : { ownerId: session.user.id }) };
  const [activeCount, reviewCount, changesCount, releaseRows, nextRelease] = await Promise.all([
    prisma.release.count({ where: { ...where, status: { notIn: ["RELEASED", "REJECTED"] } } }),
    prisma.release.count({ where: { ...where, status: { in: ["SUBMITTED", "IN_REVIEW", "RESUBMITTED"] } } }),
    prisma.release.count({ where: { ...where, status: "CHANGES_REQUESTED" } }),
    prisma.release.findMany({ where, take: 4, orderBy: { updatedAt: "desc" }, include: { artists: { include: { artist: true } }, artwork: true, _count: { select: { tracks: true } } } }),
    prisma.release.findFirst({ where: { ...where, desiredDate: { gte: new Date() }, status: { notIn: ["RELEASED", "REJECTED"] } }, orderBy: { desiredDate: "asc" }, include: { artists: { include: { artist: true } } } }),
  ]);
  const releaseList: ReleaseCardData[] = releaseRows.map((release, index) => ({
    id: release.id, title: release.title, artist: release.artists.map(({ artist }) => artist.name).join(", ") || session.user.name,
    type: `${release.type === "SINGLE" ? "Single" : release.type === "EP" ? "EP" : "Album"} · ${release._count.tracks} ${release._count.tracks === 1 ? "track" : "tracks"}`,
    date: release.desiredDate ? new Intl.DateTimeFormat("en", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(release.desiredDate).toUpperCase() : "DATE TBD",
    status: release.status.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (char) => char.toUpperCase()), tone: ["cover-blue", "cover-sand", "cover-rose", "cover-green"][index % 4], cover: release.title.slice(0, 2).toUpperCase(), artworkUrl: release.artwork ? `/api/releases/${release.id}/files?kind=artwork` : undefined,
  }));
  const welcomeName = session.user.name.split(" ")[0];
  return <div className="shell">
    <aside className="sidebar"><Link className="brand" href="/"><span className="brand-mark">90<span>°</span></span><span className="brand-name">NynetyDegrees<small>ARTIST PORTAL</small></span></Link><div className="workspace-switch"><span className="workspace-avatar">N</span><span><b>NynetyDegrees</b><small>Independent label</small></span><ChevronDown size={15} /></div><div className="nav-caption">WORKSPACE</div><nav aria-label="Main navigation">{nav.map(({ name, icon: Icon, active }) => <Link key={name} href={name === "Overview" ? "/" : `/${name.toLowerCase()}`} className={`nav-link${active ? " active" : ""}`}><Icon size={17} strokeWidth={1.7} /><span>{name}</span>{name === "Releases" && <span className="nav-count">{String(activeCount).padStart(2, "0")}</span>}</Link>)}</nav><div className="nav-caption nav-caption-admin">LABEL</div><Link className="nav-link" href="/admin"><SlidersHorizontal size={17} strokeWidth={1.7} /><span>Review queue</span>{isStaff && reviewCount > 0 && <span className="queue-dot">{reviewCount}</span>}</Link><div className="sidebar-bottom"><div className="storage-card"><div className="storage-top"><span>Storage</span><span>Local</span></div><div className="storage-track"><i /></div><small>Files stored securely</small></div><Link className="nav-link" href="/settings"><Settings2 size={17} strokeWidth={1.7} /><span>Settings</span></Link><Link className="nav-link help-link" href="/help"><CircleHelp size={17} strokeWidth={1.7} /><span>Help &amp; support</span></Link><div className="profile"><div className="profile-avatar">{session.user.name.slice(0, 2).toUpperCase()}</div><div><b>{session.user.name}</b><small>{session.user.role === "USER" ? "Artist account" : session.user.role.toLowerCase()}</small></div><button className="icon-button" aria-label="Account menu"><ChevronDown size={15} /></button></div></div></aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumbs">Workspace <span>/</span> <b>Overview</b></div><div className="topbar-actions"><Link href="/releases" className="search-trigger" aria-label="Search releases"><Search size={15} /><span>Browse releases</span><kbd>⌘ K</kbd></Link><Link href="/settings" className="avatar-small" aria-label="Settings">{session.user.name.slice(0, 2).toUpperCase()}</Link></div></header><div className="content-wrap">
      <section className="welcome-row"><div><div className="eyebrow"><span className="eyebrow-line" /> YOUR LABEL WORKSPACE</div><h1>Good morning, {welcomeName}<span className="period">.</span></h1><p className="welcome-copy">Here’s the latest on your music.</p></div><Link href="/releases/new" className="primary-button"><Plus size={17} /> New release</Link></section>
      <section className="stat-grid" aria-label="Release summary"><div className="stat-card"><div className="stat-label">ACTIVE RELEASES <Disc3 size={15} /></div><div className="stat-value">{String(activeCount).padStart(2, "0")}</div><div className="stat-foot">Releases in your catalog</div><div className="stat-spark spark-one">{Array.from({ length: 12 }, (_, i) => <i key={i} />)}</div></div><div className="stat-card"><div className="stat-label">IN REVIEW <Activity size={15} /></div><div className="stat-value">{String(reviewCount).padStart(2, "0")}</div><div className="stat-foot"><span className="mini-dot amber" /> Submitted or being reviewed</div><div className="review-indicator"><span/><span/><span/><span/><span/><span/><span/></div></div><div className="stat-card"><div className="stat-label">NEEDS YOUR ATTENTION <Sparkles size={15} /></div><div className="stat-value">{String(changesCount).padStart(2, "0")}</div><Link href="/releases" className="stat-foot stat-action">View requested changes <ArrowUpRight size={12} /></Link><div className="attention-orbit"><i/><i/><i/></div></div><div className="stat-card next-drop"><div className="stat-label">NEXT RELEASE <CalendarDays size={15} /></div><div className="next-date"><b>{nextRelease?.desiredDate ? new Intl.DateTimeFormat("en", { day: "2-digit", timeZone: "UTC" }).format(nextRelease.desiredDate) : "—"}</b><span>{nextRelease?.desiredDate ? new Intl.DateTimeFormat("en", { month: "short", year: "numeric", timeZone: "UTC" }).format(nextRelease.desiredDate).toUpperCase() : "NO DATE SET"}</span></div><div className="stat-foot">{nextRelease?.artists[0]?.artist.name ?? "Add a release date"}{nextRelease ? ` · ${nextRelease.title}` : ""}</div><div className="date-mark">90°</div></div></section>
      <section className="release-section"><div className="section-heading"><div><div className="section-kicker">YOUR CATALOG</div><h2>Recent releases</h2></div><div className="section-tools"><Link href="/releases" className="filter-button"><SlidersHorizontal size={14} />All releases</Link><Link href="/releases" className="text-link">View all <ArrowUpRight size={13} /></Link></div></div>{releaseList.length ? <div className="release-list">{releaseList.map((release) => <ReleaseCard key={release.id} release={release} />)}</div> : <div className="empty-state"><Disc3 size={22}/><b>Your catalog is ready.</b><span>Create a release to get started.</span><Link href="/releases/new" className="text-link">Create your first release <ArrowUpRight size={13}/></Link></div>}</section>
      <footer className="page-footer"><span>© 2026 NynetyDegrees Records</span><span><span className="online-dot" /> All systems operational</span><span>Made for the music.</span></footer>
    </div></main><nav className="mobile-nav" aria-label="Mobile navigation"><Link className="mobile-active" href="/"><LayoutDashboard size={19}/><span>Home</span></Link><Link href="/releases"><Disc3 size={19}/><span>Releases</span></Link><Link href="/artists"><UsersRound size={19}/><span>Artists</span></Link><Link href="/admin"><AudioLines size={19}/><span>Review</span></Link></nav>
  </div>;
}
