"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, Disc3, FileAudio, ImagePlus, LoaderCircle, Plus, Trash2 } from "lucide-react";
import { uploadMultipart } from "@/app/lib/upload";

const steps = ["Release information", "Artists", "Tracks", "Contributors", "Artwork", "Release settings", "Review"];
type TrackDraft = { title: string; isrc: string; explicit: boolean; file?: File };
type CreditDraft = { name: string; role: "MUSIC" | "LYRICS" | "PRODUCER" };

export default function NewReleasePage() {
  const router=useRouter(); const [step,setStep]=useState(0); const [releaseId,setReleaseId]=useState(""); const [title,setTitle]=useState(""); const [type,setType]=useState("SINGLE"); const [genre,setGenre]=useState(""); const [language,setLanguage]=useState("English"); const [explicit,setExplicit]=useState(false); const [date,setDate]=useState(""); const [artist,setArtist]=useState("");const[featuringArtist,setFeaturingArtist]=useState(""); const [tracks,setTracks]=useState<TrackDraft[]>([{title:"",isrc:"",explicit:false}]); const [credits,setCredits]=useState<CreditDraft[]>([]); const [artwork,setArtwork]=useState<File>(); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [saved,setSaved]=useState(false);const[uploadState,setUploadState]=useState<{name:string;progress:number}|null>(null);
  const headers={"Content-Type":"application/json"};
  async function persistRelease(){if(!releaseId){const response=await fetch("/api/releases",{method:"POST",headers,body:JSON.stringify({title,type,genre,language,explicit,desiredDate:date})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not save release");setReleaseId(data.id);sessionStorage.setItem("nynety-draft",data.id);return data.id;}const response=await fetch(`/api/releases/${releaseId}`,{method:"PATCH",headers,body:JSON.stringify({title,type,genre,language,explicit,desiredDate:date})});if(!response.ok)throw new Error("Could not save release");return releaseId;}
  async function saveDraft(){setBusy(true);setError("");try{await persistRelease();setSaved(true);setTimeout(()=>setSaved(false),2200);}catch(err){setError(err instanceof Error?err.message:"Could not save");}finally{setBusy(false);}}
  async function next(){setBusy(true);setError("");try{const id=await persistRelease();if(step===1){const artists=[{name:artist,role:"PRIMARY"},...(featuringArtist.trim()?[{name:featuringArtist,role:"FEATURING"}]:[])];const response=await fetch(`/api/releases/${id}/artists`,{method:"POST",headers,body:JSON.stringify({artists})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not save artist");}if(step===2){const response=await fetch(`/api/releases/${id}`,{method:"POST",headers,body:JSON.stringify({tracks:tracks.map(({title:t,isrc:i,explicit:e})=>({title:t,isrc:i,explicit:e}))})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not save tracks");const stored=await fetch(`/api/releases/${id}`);const release=await stored.json();for(let index=0;index<tracks.length;index++){const track=tracks[index];if(track.file){const form=new FormData();form.append("kind","audio");form.append("trackId",release.tracks[index].id);form.append("file",track.file);setUploadState({name:track.file.name,progress:0});await uploadMultipart(`/api/releases/${id}/files`,form,progress=>setUploadState({name:track.file!.name,progress}));}}setUploadState(null);}
      if(step===3&&credits.some(c=>c.name.trim())){const response=await fetch(`/api/releases/${id}/credits`,{method:"POST",headers,body:JSON.stringify({credits})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not save contributors");}
      if(step===4&&artwork){const form=new FormData();form.append("kind","artwork");form.append("file",artwork);setUploadState({name:artwork.name,progress:0});await uploadMultipart(`/api/releases/${id}/files`,form,progress=>setUploadState({name:artwork.name,progress}));setUploadState(null);}
      if(step===6){const response=await fetch(`/api/releases/${id}/status`,{method:"POST",headers,body:JSON.stringify({status:"SUBMITTED"})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not submit release");router.push(`/releases/${id}`);return;}setStep(step+1);
    }catch(err){setError(err instanceof Error?err.message:"Could not save changes");}finally{setUploadState(null);setBusy(false);}}
  const updateTrack=(index:number,field:keyof TrackDraft,value:string|boolean|File)=>setTracks(current=>current.map((track,i)=>i===index?{...track,[field]:value}:track));
  return <main className="wizard-page"><header className="wizard-top"><Link href="/" className="wizard-back"><ArrowLeft size={15}/> Back to dashboard</Link><div className="wizard-brand"><b>90<span>°</span></b> RELEASE STUDIO</div><button onClick={saveDraft} disabled={busy} className="save-draft">{saved?<><Check size={14}/> Saved</>:"Save draft"}</button></header><div className="wizard-shell"><aside className="wizard-steps"><div className="section-kicker">NEW RELEASE</div><h1>Let’s get your<br/>music out there.</h1><p>Everything you need to share your release with the world.</p><ol>{steps.map((label,index)=><li key={label} className={index===step?"current":index<step?"done":""}><span>{index<step?<Check size={12}/>:`0${index+1}`}</span><b>{label}</b></li>)}</ol><div className="wizard-aside-note"><Disc3 size={16}/><span>Drafts save automatically as you go.</span></div></aside><section className="wizard-panel"><div className="wizard-progress"><span>STEP {String(step+1).padStart(2,"0")} <i>/ 07</i></span><div>{steps.map((s,i)=><i key={s} className={i<=step?"filled":""}/>)}</div></div><div className="wizard-body">
    {step===0&&<><div className="section-kicker">THE BASICS</div><h2>Tell us about this release</h2><p className="wizard-intro">Start with the details listeners will see first.</p><label className="field-label">Release title<input className="field-input" autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Give your release a name" maxLength={120}/></label><label className="field-label">Release type<div className="choice-grid">{[["SINGLE","Single"],["EP","EP"],["ALBUM","Album"]].map(([val,label])=><button key={val} className={`choice${type===val?" selected":""}`} onClick={()=>setType(val)} type="button"><span className="choice-radio"/><b>{label}</b><small>{val==="SINGLE"?"1 track":val==="EP"?"2–6 tracks":"7+ tracks"}</small></button>)}</div></label></>}
    {step===1&&<><div className="section-kicker">THE PEOPLE</div><h2>Who’s performing?</h2><p className="wizard-intro">Add the primary artist and any featured performer.</p><label className="field-label">Primary artist<input className="field-input" value={artist} onChange={e=>setArtist(e.target.value)} placeholder="Artist or band name" maxLength={120}/></label><label className="field-label">Featuring artist <span className="optional-label">OPTIONAL</span><input className="field-input" value={featuringArtist} onChange={e=>setFeaturingArtist(e.target.value)} placeholder="Featured performer" maxLength={120}/></label><div className="tip-panel"><Disc3 size={17}/><span>Collaborator and songwriter credits can be added in the next step.</span></div></>}
    {step===2&&<><div className="section-kicker">THE MUSIC</div><h2>Add your tracks</h2><p className="wizard-intro">Add tracks in release order. You can attach WAV or FLAC files.</p><div className="track-list">{tracks.map((track,index)=><div className="track-row" key={index}><span className="track-number">{String(index+1).padStart(2,"0")}</span><div className="track-fields"><input className="field-input" value={track.title} onChange={e=>updateTrack(index,"title",e.target.value)} placeholder="Track title"/><input className="field-input isrc-input" value={track.isrc} onChange={e=>updateTrack(index,"isrc",e.target.value)} placeholder="ISRC (optional)"/><label className="upload-mini"><FileAudio size={14}/>{track.file?track.file.name:"Choose audio"}<input type="file" accept=".wav,.flac,audio/wav,audio/flac" onChange={e=>e.target.files?.[0]&&updateTrack(index,"file",e.target.files[0])}/></label><button type="button" className="remove-track" aria-label="Remove track" onClick={()=>setTracks(current=>current.filter((_,i)=>i!==index))}><Trash2 size={14}/></button></div><label className="explicit-check"><input type="checkbox" checked={track.explicit} onChange={e=>updateTrack(index,"explicit",e.target.checked)}/> Explicit lyrics</label></div>)}</div><button className="add-track" type="button" onClick={()=>setTracks(current=>[...current,{title:"",isrc:"",explicit:false}])}><Plus size={14}/> Add another track</button></>}
    {step===3&&<><div className="section-kicker">CREDITS</div><h2>Give credit where it’s due</h2><p className="wizard-intro">List songwriters and producers for this release.</p><div className="credit-list">{credits.map((credit,index)=><div className="credit-row" key={index}><input className="field-input" value={credit.name} onChange={e=>setCredits(current=>current.map((c,i)=>i===index?{...c,name:e.target.value}:c))} placeholder="Contributor name"/><select className="field-input" value={credit.role} onChange={e=>setCredits(current=>current.map((c,i)=>i===index?{...c,role:e.target.value as CreditDraft["role"]}:c))}><option value="MUSIC">Music</option><option value="LYRICS">Lyrics</option><option value="PRODUCER">Producer</option></select><button type="button" className="remove-track" aria-label="Remove contributor" onClick={()=>setCredits(current=>current.filter((_,i)=>i!==index))}><Trash2 size={14}/></button></div>)}</div><button className="add-track" type="button" onClick={()=>setCredits(current=>[...current,{name:"",role:"MUSIC"}])}><Plus size={14}/> Add contributor</button></>}
    {step===4&&<><div className="section-kicker">THE ARTWORK</div><h2>Make a first impression</h2><p className="wizard-intro">Upload square artwork in JPG or PNG format.</p><label className="artwork-drop"><ImagePlus size={27}/><b>{artwork?.name??"Drop artwork here"}</b><span>{artwork?`${(artwork.size/1024/1024).toFixed(1)} MB · ${artwork.type}`:"or browse files · JPG / PNG · up to 20 MB"}</span><input type="file" accept=".jpg,.jpeg,.png,image/jpeg,image/png" onChange={e=>setArtwork(e.target.files?.[0])}/></label></>}
    {step===5&&<><div className="section-kicker">RELEASE SETTINGS</div><h2>Set the scene</h2><p className="wizard-intro">A few final details help us prepare your release.</p><div className="settings-grid"><label className="field-label">Genre<input className="field-input" value={genre} onChange={e=>setGenre(e.target.value)} placeholder="e.g. Alternative pop" maxLength={60}/></label><label className="field-label">Language<select className="field-input" value={language} onChange={e=>setLanguage(e.target.value)}><option>English</option><option>Spanish</option><option>French</option><option>Japanese</option><option>Other</option></select></label><label className="field-label">Requested release date<input className="field-input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="explicit-setting"><input type="checkbox" checked={explicit} onChange={e=>setExplicit(e.target.checked)}/><span><b>Contains explicit content</b><small>Marks this release as explicit on streaming services.</small></span></label></div></>}
    {step===6&&<><div className="section-kicker">ONE LAST LOOK</div><h2>Ready when you are.</h2><p className="wizard-intro">Review your details before sending your release to the label team.</p><div className="review-card"><div className="review-art">{artwork?<span>{artwork.name.slice(0,2).toUpperCase()}</span>:<ImagePlus size={20}/>}</div><div className="review-title"><h3>{title||"Untitled release"}</h3><p>{artist||"Artist not added"} · {type}</p></div><div className="review-divider"/><div className="review-detail"><span>TRACKS</span><b>{tracks.length} {tracks.length===1?"track":"tracks"}</b></div><div className="review-detail"><span>GENRE</span><b>{genre||"Not specified"}</b></div><div className="review-detail"><span>RELEASE DATE</span><b>{date||"To be confirmed"}</b></div></div><div className="tip-panel"><Check size={16}/><span>By submitting, your release will be reviewed by our label team. You can still make changes if it’s returned to you.</span></div></>}
    {uploadState&&<div className="upload-progress"><div><span>{uploadState.name}</span><b>{uploadState.progress}%</b></div><i><span style={{width:`${uploadState.progress}%`}}/></i></div>}{error&&<div className="wizard-error" role="alert">{error}</div>}
    </div><div className="wizard-footer"><button className="wizard-prev" type="button" onClick={()=>step===0?router.push("/"):setStep(step-1)}>{step===0?"Cancel":<><ArrowLeft size={14}/> Previous</>}</button><div><button className="wizard-next" disabled={busy||(step===0&&!title.trim())||(step===1&&!artist.trim())||(step===2&&(tracks.length===0||tracks.some(t=>!t.title.trim())))} onClick={next} type="button">{busy?<LoaderCircle className="spin" size={15}/>:step===6?<>Submit for review <ArrowRight size={14}/></>:<>Continue <ArrowRight size={14}/></>}</button></div></div></section></div><footer className="wizard-page-footer"><span>© 2026 NynetyDegrees Records</span><span>Need help? <a href="/help">Contact your label manager</a></span></footer></main>;
}
