"use client";

import Image from "next/image";
import { useState } from "react";
import { ArrowDownToLine, ArrowUpRight, Check, Clock3, FileAudio, Image as ImageIcon, Music2, Send, Upload } from "lucide-react";
import { uploadMultipart } from "@/app/lib/upload";

type ReleaseData={id:string;ownerId:string;title:string;type:string;status:string;genre:string|null;language:string|null;explicit:boolean;desiredDate:string|null;createdAt:string;updatedAt:string;owner:{name:string;email:string};artists:{name:string;role:string}[];tracks:{id:string;title:string;trackNumber:number;isrc:string|null;explicit:boolean;audioFile:{originalName:string;sizeBytes:number;mimeType:string}|null}[];contributors:{name:string;role:string}[];artwork:{originalName:string}|null;comments:{id:string;body:string;createdAt:string;author:{name:string;role:string}}[];statusHistory:{id:string;fromStatus:string|null;toStatus:string;note:string|null;createdAt:string;actor:{name:string;role:string}}[];user:{id:string;name:string;role:string}};
const tabs=["Overview","Tracks","Metadata","Files","Comments","History"];
const labels:Record<string,string>={DRAFT:"Draft",SUBMITTED:"Submitted",IN_REVIEW:"In review",CHANGES_REQUESTED:"Changes requested",RESUBMITTED:"Resubmitted",APPROVED:"Approved",READY_FOR_DISTRIBUTION:"Ready for distribution",DISTRIBUTED:"Distributed",SCHEDULED:"Scheduled",RELEASED:"Released",REJECTED:"Rejected"};
const date=(value:string)=>new Intl.DateTimeFormat("en",{day:"2-digit",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(value));
const size=(n:number)=>n<1024*1024?`${(n/1024).toFixed(0)} KB`:`${(n/1024/1024).toFixed(1)} MB`;

export default function ReleaseDetail({release:r}:{release:ReleaseData}){
  const[tab,setTab]=useState("Overview");const[note,setNote]=useState("");const[comment,setComment]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[done,setDone]=useState("");const[status,setStatus]=useState(r.status);const[comments,setComments]=useState(r.comments);const[artwork,setArtwork]=useState(r.artwork);const[tracks,setTracks]=useState(r.tracks);const[title,setTitle]=useState(r.title);const[genre,setGenre]=useState(r.genre??"");const[language,setLanguage]=useState(r.language??"English");const[releaseType,setReleaseType]=useState(r.type);const[explicit,setExplicit]=useState(r.explicit);const[desiredDate,setDesiredDate]=useState(r.desiredDate?.slice(0,10)??"");const[uploadState,setUploadState]=useState<{name:string;progress:number}|null>(null);
  const staff=r.user.role!=="USER";const own=r.user.id===r.ownerId;const editable=own&&["DRAFT","CHANGES_REQUESTED"].includes(status);
  async function changeStatus(next:string){setBusy(true);setError("");try{const response=await fetch(`/api/releases/${r.id}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:next,...(next==="CHANGES_REQUESTED"?{note}:{})})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not update status");setStatus(next);if(note&&next==="CHANGES_REQUESTED"){setComments(prev=>[...prev,{id:crypto.randomUUID(),body:note,createdAt:new Date().toISOString(),author:{name:r.user.name,role:r.user.role}}]);setNote("");setTab("Comments");}setDone("Status updated");setTimeout(()=>setDone(""),2200);}catch(e){setError(e instanceof Error?e.message:"Could not update status");}finally{setBusy(false);}}
  async function addComment(){if(!comment.trim())return;setBusy(true);setError("");try{const response=await fetch(`/api/releases/${r.id}/comments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:comment})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not add comment");setComments(prev=>[...prev,data]);setComment("");}catch(e){setError(e instanceof Error?e.message:"Could not add comment");}finally{setBusy(false);}}
  async function saveMetadata(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{const response=await fetch(`/api/releases/${r.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,type:releaseType,genre,language,explicit,desiredDate})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not save release details");setDone("Release details saved");setTimeout(()=>setDone(""),2200);}catch(e){setError(e instanceof Error?e.message:"Could not save release details");}finally{setBusy(false);}}
  async function saveTrack(track:{id:string;title:string;isrc:string|null;explicit:boolean}){setBusy(true);setError("");try{const response=await fetch(`/api/releases/${r.id}/tracks/${track.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:track.title,isrc:track.isrc??"",explicit:track.explicit})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not save track details");setDone("Track details saved");setTimeout(()=>setDone(""),2200);}catch(e){setError(e instanceof Error?e.message:"Could not save track details");}finally{setBusy(false);}}
  async function upload(file:File,kind:"audio"|"artwork",trackId?:string){setBusy(true);setError("");setUploadState({name:file.name,progress:0});try{const form=new FormData();form.append("kind",kind);if(trackId)form.append("trackId",trackId);form.append("file",file);const data=await uploadMultipart(`/api/releases/${r.id}/files`,form,progress=>setUploadState({name:file.name,progress}));if(kind==="artwork")setArtwork({originalName:String(data.name)});else setTracks(current=>current.map(t=>t.id===trackId?{...t,audioFile:{originalName:String(data.name),sizeBytes:Number(data.size),mimeType:String(data.mimeType)}}:t));setDone("File uploaded");setTimeout(()=>setDone(""),2200);}catch(e){setError(e instanceof Error?e.message:"Could not upload file");}finally{setUploadState(null);setBusy(false);}}
  return <div className="release-detail"><div className="detail-overline"><div className="section-kicker">RELEASE WORKSPACE <span>/</span> {r.type}</div>{staff&&<span className="admin-role">{r.owner.name} · {r.owner.email}</span>}</div><div className="detail-heading"><div><h1>{title}</h1><p>{r.artists.map(a=>a.name).join(", ")||r.owner.name} <span>·</span> {r.tracks.length} {r.tracks.length===1?"track":"tracks"}</p></div><span className={`status status-${labels[status].toLowerCase().replaceAll(" ","-")}`}><i/>{labels[status]}</span></div><div className="detail-tabs" role="tablist" aria-label="Release sections">{tabs.map(label=><button key={label} role="tab" aria-selected={tab===label} className={tab===label?"selected":""} onClick={()=>setTab(label)}>{label}{label==="Comments"&&comments.length>0&&<small>{comments.length}</small>}</button>)}</div>
  {tab==="Overview"&&<div className="detail-grid"><section className="detail-card artwork-card"><div className="section-kicker">COVER ART</div><div className="detail-art">{artwork?<Image fill unoptimized sizes="(max-width: 760px) 100vw, 35vw" src={`/api/releases/${r.id}/files?kind=artwork`} alt={`${r.title} cover art`}/>:<div className="detail-art-empty"><ImageIcon size={25}/><span>No artwork uploaded</span></div>}</div>{own&&["DRAFT","CHANGES_REQUESTED"].includes(status)&&<label className="upload-control"><Upload size={14}/> {artwork?"Replace artwork":"Upload artwork"}<input type="file" accept=".jpg,.jpeg,.png,image/jpeg,image/png" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"artwork")}/></label>}</section><section className="detail-card"><div className="section-kicker">RELEASE DETAILS</div><dl className="detail-list"><div><dt>Release type</dt><dd>{r.type}</dd></div><div><dt>Release date</dt><dd>{r.desiredDate?date(r.desiredDate):"Not set"}</dd></div><div><dt>Primary artist</dt><dd>{r.artists.map(a=>a.name).join(", ")||r.owner.name}</dd></div><div><dt>Genre</dt><dd>{r.genre||"Not specified"}</dd></div><div><dt>Language</dt><dd>{r.language||"Not specified"}</dd></div><div><dt>Explicit</dt><dd>{r.explicit?"Yes":"No"}</dd></div><div><dt>Last updated</dt><dd>{date(r.updatedAt)}</dd></div></dl></section><section className="detail-card track-overview"><div className="detail-card-head"><div><div className="section-kicker">TRACKLIST</div><h2>{r.tracks.length} tracks</h2></div><button className="inline-link" onClick={()=>setTab("Tracks")}>View all <ArrowUpRight size={13}/></button></div>{r.tracks.slice(0,3).map(t=><div className="track-preview" key={t.id}><span>{String(t.trackNumber).padStart(2,"0")}</span><b>{t.title}</b>{t.explicit&&<small>E</small>}{t.audioFile&&<span className="audio-ok"><Check size={12}/></span>}</div>)}</section><section className="detail-card status-card"><div className="section-kicker">WORKFLOW</div><div className="status-timeline">{r.statusHistory.map((event,i)=><div className="status-event" key={event.id}><span className="status-node">{i===r.statusHistory.length-1?<Check size={10}/>:null}</span><div><b>{labels[event.toStatus]??event.toStatus}</b><small>{event.actor.name} · {date(event.createdAt)}</small>{event.note&&<p>{event.note}</p>}</div></div>)}</div></section></div>}
  {tab==="Tracks"&&<section className="detail-card detail-wide"><div className="section-kicker">TRACKLIST</div><h2>Tracks &amp; audio files</h2>{r.tracks.length===0?<p className="detail-muted">No tracks added yet.</p>:<div className="file-list">{tracks.map(t=><div className="file-row" key={t.id}><span className="track-number">{String(t.trackNumber).padStart(2,"0")}</span><div className="file-info">{editable?<div className="track-edit"><input aria-label={`Track ${t.trackNumber} title`} value={t.title} onChange={e=>setTracks(prev=>prev.map(track=>track.id===t.id?{...track,title:e.target.value}:track))}/><input aria-label={`Track ${t.trackNumber} ISRC`} value={t.isrc??""} onChange={e=>setTracks(prev=>prev.map(track=>track.id===t.id?{...track,isrc:e.target.value}:track))} placeholder="ISRC"/><label><input type="checkbox" checked={t.explicit} onChange={e=>setTracks(prev=>prev.map(track=>track.id===t.id?{...track,explicit:e.target.checked}:track))}/> Explicit</label><button className="inline-link" disabled={busy} onClick={()=>saveTrack(t)}>Save track</button></div>:<><b>{t.title}{t.explicit&&<small className="explicit-tag">EXPLICIT</small>}</b><span>{t.isrc||"ISRC not set"} {t.audioFile&&`· ${t.audioFile.originalName} · ${size(t.audioFile.sizeBytes)}`}</span></>}{t.audioFile&&<audio controls preload="none" src={`/api/releases/${r.id}/files?kind=audio&trackId=${t.id}`}/>}</div>{t.audioFile?<a className="download-button" href={`/api/releases/${r.id}/files?kind=audio&trackId=${t.id}`} download><ArrowDownToLine size={14}/></a>:editable?<label className="upload-control compact"><Upload size={13}/> Upload WAV/FLAC<input type="file" accept=".wav,.flac,audio/wav,audio/flac" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"audio",t.id)}/></label>:<span className="missing-file">No audio file</span>}</div>)}</div>}</section>}
  {tab==="Metadata"&&<div className="detail-grid"><section className="detail-card"><div className="section-kicker">ARTISTS</div>{r.artists.map(a=><div className="metadata-line" key={a.name}><Music2 size={14}/><b>{a.name}</b><span>{a.role}</span></div>)}</section><section className="detail-card"><div className="section-kicker">CONTRIBUTORS</div>{r.contributors.length?r.contributors.map((c,i)=><div className="metadata-line" key={`${c.name}-${i}`}><span className="contrib-initial">{c.name.slice(0,1)}</span><b>{c.name}</b><span>{c.role}</span></div>):<p className="detail-muted">No credits added.</p>}</section><section className="detail-card metadata-edit"><div className="section-kicker">RELEASE METADATA</div>{editable?<form className="metadata-form" onSubmit={saveMetadata}><label>Release title<input className="field-input" required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Release type<select className="field-input" value={releaseType} onChange={e=>setReleaseType(e.target.value)}><option value="SINGLE">Single</option><option value="EP">EP</option><option value="ALBUM">Album</option></select></label><label>Genre<input className="field-input" maxLength={60} value={genre} onChange={e=>setGenre(e.target.value)}/></label><label>Language<input className="field-input" maxLength={40} value={language} onChange={e=>setLanguage(e.target.value)}/></label><label>Release date<input className="field-input" type="date" value={desiredDate} onChange={e=>setDesiredDate(e.target.value)}/></label><label className="metadata-explicit"><input type="checkbox" checked={explicit} onChange={e=>setExplicit(e.target.checked)}/> Explicit content</label><button className="wizard-next" disabled={busy}>Save details</button></form>:<dl className="detail-list"><div><dt>ISRC</dt><dd>{r.tracks.map(t=>t.isrc).filter(Boolean).join(", ")||"Not specified"}</dd></div><div><dt>Language</dt><dd>{r.language||"Not specified"}</dd></div><div><dt>Genre</dt><dd>{r.genre||"Not specified"}</dd></div><div><dt>Explicit</dt><dd>{r.explicit?"Yes":"No"}</dd></div></dl>}</section></div>}
  {tab==="Files"&&<section className="detail-card detail-wide"><div className="section-kicker">FILE LIBRARY</div><h2>Release files</h2>{artwork&&<div className="file-row"><ImageIcon size={17}/><div className="file-info"><b>{artwork.originalName}</b><span>Artwork · private storage</span></div><a className="download-button" href={`/api/releases/${r.id}/files?kind=artwork`} download><ArrowDownToLine size={14}/></a></div>}{tracks.filter(t=>t.audioFile).map(t=><div className="file-row" key={t.id}><FileAudio size={17}/><div className="file-info"><b>{t.audioFile?.originalName}</b><span>{t.title} · {size(t.audioFile?.sizeBytes??0)}</span></div><a className="download-button" href={`/api/releases/${r.id}/files?kind=audio&trackId=${t.id}`} download><ArrowDownToLine size={14}/></a></div>)}{!artwork&&!tracks.some(t=>t.audioFile)&&<p className="detail-muted">No files uploaded yet.</p>}</section>}
  {tab==="Comments"&&<section className="detail-card detail-wide"><div className="section-kicker">RELEASE DISCUSSION</div><h2>Comments</h2><div className="comment-list">{comments.length?comments.map(c=><article className="comment" key={c.id}><div className="comment-avatar">{c.author.name.slice(0,2).toUpperCase()}</div><div><div className="comment-head"><b>{c.author.name}</b><span>{c.author.role}</span><time>{date(c.createdAt)}</time></div><p>{c.body}</p></div></article>):<p className="detail-muted">No comments yet.</p>}</div><div className="comment-compose"><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Leave a note for the release team…" maxLength={2000}/><button className="wizard-next" onClick={addComment} disabled={busy||!comment.trim()}><Send size={14}/> Send</button></div></section>}
  {tab==="History"&&<section className="detail-card detail-wide"><div className="section-kicker">AUDIT TRAIL</div><h2>Status history</h2><div className="status-timeline history-list">{r.statusHistory.map(event=><div className="status-event" key={event.id}><span className="status-node"><Clock3 size={10}/></span><div><b>{event.fromStatus?`${labels[event.fromStatus]} → `:""}{labels[event.toStatus]}</b><small>{event.actor.name} · {event.actor.role} · {date(event.createdAt)}</small>{event.note&&<p>{event.note}</p>}</div></div>)}</div></section>}
  {staff&&["SUBMITTED","IN_REVIEW","RESUBMITTED"].includes(status)&&<section className="moderation-panel"><div><div className="section-kicker">MANAGER REVIEW</div><b>Move this release forward</b><p>Every decision will be logged in the release history.</p></div><div className="moderation-actions">{status==="SUBMITTED"&&<button className="subtle-button" disabled={busy} onClick={()=>changeStatus("IN_REVIEW")}>Start review</button>}<button className="subtle-button reject" disabled={busy} onClick={()=>setTab("Comments")}>Add feedback</button><button className="primary-button" disabled={busy} onClick={()=>changeStatus("APPROVED")}><Check size={14}/> Approve</button><div className="request-changes"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="What should be updated?" maxLength={2000}/><button disabled={busy||!note.trim()} onClick={()=>changeStatus("CHANGES_REQUESTED")}>Request changes</button></div></div></section>}
  {own&&status==="DRAFT"&&<section className="moderation-panel"><div><div className="section-kicker">READY FOR REVIEW?</div><b>Submit your release</b><p>Make sure your tracks and artwork are ready for review.</p></div><button className="primary-button" disabled={busy} onClick={()=>changeStatus("SUBMITTED")}>Submit for review <ArrowUpRight size={14}/></button></section>}
  {own&&status==="CHANGES_REQUESTED"&&<section className="moderation-panel"><div><div className="section-kicker">UPDATES COMPLETE?</div><b>Resubmit your release</b><p>Make the requested updates, then send it back to the label team.</p></div><button className="primary-button" disabled={busy} onClick={()=>changeStatus("RESUBMITTED")}>Resubmit <ArrowUpRight size={14}/></button></section>}
  {uploadState&&<div className="upload-progress"><div><span>{uploadState.name}</span><b>{uploadState.progress}%</b></div><i><span style={{width:`${uploadState.progress}%`}}/></i></div>}{error&&<div className="detail-error" role="alert">{error}</div>}{done&&<div className="detail-toast" role="status"><Check size={13}/>{done}</div>}
  </div>
}
